### ISSUE TITLE
Readme improvements

### ISSUE THREAD

**Issue by bradrf** [monadicstack/frodo#47]
In trying to use Frodo for the first time, I think some of the following changes might be helpful for folks:

- Note that you MUST end interface names with the keyword `Service` or it won't be found
- It's not clear what the VERSION docopt does
- Mention go generate ./... will "do the right thing" if you have multiple services defined
- Mention that the responses MUST be structs (i.e. you can't return an array of objects, e.g. when you implement "get the list of all things")

**Comment by robsignorelli** [comment]
Addressing each suggestion:

* Definitely a good point to get across. I'll add something explicit to the docs, but I will also update the `frodo` CLI to output a more descriptive error when it doesn't find any. Currently it just tells you that it couldn't find any service interfaces. I will make the output include that nugget of info as well so that it's clear even if you didn't grok everything in the docs.
* VERSION literally just regurgitates that value if you generate swagger documentation. Can you think of an actual legit case where that value would be useful elsewhere? If it is just to round out your swagger/OpenAPI docs, I might just move the nugget about the VERSION option to the swagger docs section so the info is closer to the more relevant area.
* I like the suggestion about the go generate shortcut.
* Just like the "Service" suffix, I can add a blurb to the docs that might be easy to miss, so I'll also look at having the CLI give you the feedback at the appropriate time as well.

I had a couple of other README updates I needed to make as well, so I'll include these with my in-process updates.

**Comment by bradrf** [comment]
Thanks, Rob! Re:VERSION, seems like it'd be better as a variable you can pass along to the framework instead of needed it to live within the docs. Most apps embed a value at build time... which would be hard to pass along into a comment.

**Comment by robsignorelli** [comment]
I've merged the README changes and CLI output updates into main. I'll tag them as part of a v1.1.1 once I knock off a few of the other things Brad found.
