### ISSUE TITLE
Requests for unregistered paths should be logged (or loggable)

### ISSUE THREAD

**Issue by bradrf** [monadicstack/frodo#49]
A request for a resource not configured should be able to be logged by middleware or perhaps through an optional callback provided for tracking or responding appropriately (i.e. custom 404 handler).

**Comment by robsignorelli** [comment]
You definitely should be able to have some sort of pluggable handler rather than just a logger. I'm having a mental block as to what form the destroyer should take. I'm of two minds on this one. There are two paths I can take.

First, provide another `rpc.WithNotFound()` that accepts an `http.HandlerFunc`:

```go
func Missing(w http.ResponseWriter, req *http.Request) {
    // do stuff
}

func main() {
    // normal setup stuff...
    gateway := calcrpc.NewCalculatorServiceGateway(":8080",
        rpc.WithNotFound(Missing),
    )
    // ...
}
```

It's fairly standard, but part of the "shtick" of Frodo is that it tries to keep you out of HTTP-land as much as possible. The other possibility I am considering is something that looks more like one of your typical service functions.

```go
func Missing(ctx context.Context, req interface{}) (interface{}, error) {
    return nil, errors.NotFound("brain")
}

func main() {
    // normal setup stuff...
    gateway := calcrpc.NewCalculatorServiceGateway(":8080",
        rpc.WithNotFound(Missing),
    )
    // ...
}
```

The second one feels more "Frodo-y" as you can still use the errors package to easily dictate status codes and aren't manually mucking with HTTP stuff.

**Comment by bradrf** [comment]
Yes, I agree, the second one seems more apropos for Frodo.

**Comment by robsignorelli** [comment]
Aaaand I went with option C. None of the above. After writing some code in both styles, both felt irritating in different ways. When using the standard `HttpHandlerFunc` style it forced the user to re-implement the status code and header management that you get with the default handlers just so you could also have logging (or whatever). The service function style had the issue that it was hard to make it clear how to customize the status code. It could easily default to 404, but if you wanted to customize the headers/code then it was not clear how to do that. Do you return an error? Do you return a response value? It just wasn't clear how you'd use it properly.

So... I opted for having you provide a list of `MiddlewareFunc`. The rationale is that it let me preserve the router's default handling for missing routes, but you can easily chain your existing loggers, telemetry, etc. together. Chances are you don't really want to change the handling behavior - you just want to log the requests, update your grafana graphs, etc. But if you do want to provide your own handler whole-hog, you can just not call `next()` to short circuit the default behavior.

I've added some docs in the README that show how to (A) augment the default handling behavior and (B) how to completely rewrite the response as you see fit.

https://github.com/monadicstack/frodo#handling-not-found

**Comment by bradrf** [comment]
Makes sense! :+1:
