### ISSUE TITLE
Multipart support

### ISSUE THREAD

**Issue by davidrenne** [monadicstack/frodo#65]
How can I post a multipart form upload into an RPC that frodo is hosting?  Do you have any advice for me?  Or do I have to host a standard webserver to handle file uploads?

**Comment by robsignorelli** [comment]
Sorry for the bananas late response to this. I'm sure you've moved on from this issue long ago. On the off chance some poor soul stumbles upon this later, here's my input on this. I punted on supporting multipart uploads. I did, at one point, start to implement it, but I absolutely hated the implementation and scrapped it and never came back to it.

The way I usually handle this case is to not have the service accept the file directly, at all. Instead, I implement this flow:

- Client requests a service endpoint that responds with a pre-signed S3 upload URL (or your object store of choice) and some id unique to this upload.
- Client uploads the file directly to S3 using that URL. The S3 location is usually in some temp bucket.
- Client makes another request to the service with the unique upload id to the operation that actually needs the file. Once the work is done, we can either delete the file or move it to a bucket where it will live on.

Obviously that is very dependent on how/where you deploy, but I generally prefer this over having the services accept the file for these reasons:

- It frees up a bunch of resources on your service to do what the service is really meant for. I've done it the other way and when dealing with large uploads or a lot of uploads, too many compute resources get spent moving bytes from one computer to another. This way, your service gets to stick to just the business logic work it was built for.
- If you have a bunch of slow uploads, that can really mess with auto-scaling or health checks that are based on concurrent requests. Uploading directly to S3 means that those really long-lived connections are handled outside of your service infrastructure.
- If I'm dealing with files, it's likely ending up in my object store anyway, so it cuts out the middleman.
- Since you're putting it on your object store, you can use bucket policies to automatically purge files when their done or when they're abandoned w/o having been processed.

On the flip side, it does mean that something that was once 1 big request is now 3 smaller requests. It's a trade-off that I've typically been happy to make because the request overhead is usually overshadowed by the upload time anyway.

**Comment by davidrenne** [comment]
I ended up just base64 encoding a 30mb file using javascript and sending it up the rpcs as a string.  Worked fine.
